name: iso
description: A test in running a background server in an Isolate
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

  network_info_plus: ^3.0.3

  qr_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.0

flutter:
  uses-material-design: true
